### PR TITLE
Chore/misc tweaks

### PR DESCRIPTION
**Pull request by zmyrgel**
update todo list and fix unregister function

### CODE REVIEW

**Comment by omar-polo** [comment]
+1 for the comments changes, I had in mind to do something like that.

There is only one things that still needs to be fixed, and I apologies for yet another request, but the pcase doesn't seem right.  The first argument needs to be an expression, `(pcase (status (...))` doesn't bind `status`, tries to call it.

I feel like this is mostly my fault at asking you to keep the `unregister` functions.  I thought it was interactively callable, not a nice-to-have for the switch vc backend stuff, sorry.

**Comment by zmyrgel** [comment]
Requests are fine, makes things better. Should we just remove the whole unregister?

**Comment by omar-polo** [comment]
I'm tempted to say to keep the unregister since it's practically finished, but I dislike providing a feature that we haven't really tested. (honestly, I didn't knew vc had the ability to switch control of files between vcs).  If you don't have objections, let's drop it.  If someone is crazy enough to use something like that, he/she will surely be able to implement it (or take the version from the history) and test it by himself.

**Comment by omar-polo** [comment]
Thanks!

**Pull request merged**
